networks:
  db:
    driver: bridge
services:
  db:
    container_name: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    image: postgres
    networks:
      - db
    ports:
      - 5433:5432
    restart: unless-stopped
    volumes:
      - db:/data/postgres
volumes:
  db:
