services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - 5433:5432
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: